Feat/trace fields
softwaregroup-bg/ut-codec-iso8583 pull request #23
Opened 2019-09-11 04:51 UTC by bloc4ain

2019-09-11 07:04 UTC, Kristiyan-Todorov approved these changes

2019-09-11 08:27 UTC, kalinkrustev requested changes

2019-09-11 08:27 UTC, kalinkrustev commented on index.js
> +            $meta.trace = this.getTrace(message);
I suggest using ut-function.template (https://github.com/softwaregroup-bg/ut-function/tree/master/packages/template)
```js
$meta.trace = this.template(message)
```
this.template can be set to:
```js
const template = require('ut-function.template');
this.template = template(config.traceFields || "${(message.mtid || '00').substr(0, 2)}${message[11]}", ['message']);
```

2019-09-11 14:11 UTC, zetxx requested changes
per comment: https://github.com/softwaregroup-bg/ut-codec-iso8583/pull/23/files#r323117518

2019-09-12 09:49 UTC, tinternet commented on index.js
> +            $meta.trace = this.getTrace(message);
Looks better now

2019-09-12 10:12 UTC, zetxx approved these changes

2019-09-12 11:53 UTC, kalinkrustev approved these changes

2019-09-20 06:39 UTC, merged